# Generated by Django 4.2.4 on 2023-08-19 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PythonVersion',
            fields=[
                ('version_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('release_date', models.DateField()),
                ('end_of_life_date', models.DateField(blank=True, null=True)),
                ('is_supported', models.BooleanField(default=True)),
                ('doc_url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoVersion',
            fields=[
                ('version_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('release_date', models.DateField()),
                ('end_of_life_date', models.DateField(blank=True, null=True)),
                ('is_supported', models.BooleanField(default=True)),
                ('doc_url', models.URLField()),
                ('is_lts', models.BooleanField(default=False)),
                ('supported_python', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='versions.pythonversion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
